kind: pipeline
type: docker
name: default

steps:
- name: fixperms
  image: imrehg/archlinux-makepkg
  user: root
  commands:
  - chown -R builder:builder .
- name: build
  image: imrehg/archlinux-makepkg
  commands:
  - yay -Syu --noconfirm
  - namcap PKGBUILD
  - makepkg -sci --noconfirm
  - namcap *.pkg.tar.xz
- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: '*.pkg.tar.xz'
    draft: true
